modLoader="javafml"
loaderVersion="*"
license='MIT'

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Joespeph, RXJpaw"
authors="ElocinDev"
description='''
An utility library for my mods!
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"
